---
- name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
  include_vars:
    file: "vars/{{ PROJECT }}_{{ ENV }}.yml" 
# tasks file for CREATEEC2
- ec2 :
    region : "{{ REGION }}"
    key_name: "{{ KEYNAME }}"
    instance_type: t2.micro
    image: "{{ IMAGE }}"
    wait: yes
    group: "{{ SGNAME }}"
    vpc_subnet_id: "{{ SUBID }}"
    assign_public_ip: yes
